import { HospitalPerformanceSnapshot } from '../types/kpis';

export const hospitalPerformanceSnapshot: HospitalPerformanceSnapshot = {
  updatedAt: '2024-06-30T08:30:00-03:00',
  criticalKPIs: [
    {
      id: 'ocupacao-total',
      titulo: 'Taxa de Ocupação Hospitalar',
      valor: '92,5%',
      meta: '95,0% meta crítica',
      variacao: '+2,4pp vs mês anterior',
      descricao: 'Capacidade consolidada dos 512 leitos monitorados (UTI + enfermarias).',
      severidade: 'critico',
      icon: 'bed-double',
    },
    {
      id: 'tempo-permanencia',
      titulo: 'Tempo Médio de Permanência',
      valor: '4,2 dias',
      meta: '≤ 4,0 dias',
      variacao: '-0,3 dia em 60 dias',
      descricao: 'Monitoramento do LOS com recorte por linha clínica e complexidade.',
      severidade: 'grave',
      icon: 'timer',
    },
    {
      id: 'taxa-reinternacao',
      titulo: 'Taxa de Reinternação 30 dias',
      valor: '8,5%',
      meta: '≤ 8,0%',
      variacao: '-0,6pp',
      descricao: 'Pacientes readmitidos em até 30 dias com destaque para especialidades críticas.',
      severidade: 'grave',
      icon: 'activity',
    },
    {
      id: 'satisfacao-paciente',
      titulo: 'Índice de Satisfação dos Pacientes',
      valor: '4,2 / 5,0',
      meta: '≥ 4,4',
      variacao: '+0,2 pontos',
      descricao: 'Avaliação multicanal NPS + pesquisas digitais com corte por unidade.',
      severidade: 'atencao',
      icon: 'heart-pulse',
    },
    {
      id: 'margem-operacional',
      titulo: 'Margem Operacional Ajustada',
      valor: '18,6%',
      meta: '≥ 17%',
      variacao: '+1,8pp',
      descricao: 'Resultado operacional considerando mix SUS/Convênios e custos indiretos.',
      severidade: 'estavel',
      icon: 'dollar-sign',
    },
    {
      id: 'aderencia-protocolos',
      titulo: 'Aderência Protocolos Críticos',
      valor: '86%',
      meta: '≥ 90%',
      variacao: '+4pp',
      descricao: 'Cumprimento de bundles clínicos (sepse, TEV, segurança cirúrgica).',
      severidade: 'atencao',
      icon: 'shield-alert',
    },
  ],
  ranking: {
    topPerformers: [
      { unidade: 'UTI Geral', score: 94.2, variacao: 2.3, severidade: 'estavel' },
      { unidade: 'Centro Cirúrgico', score: 91.8, variacao: 1.9, severidade: 'estavel' },
      { unidade: 'Oncologia', score: 90.6, variacao: 2.1, severidade: 'estavel' },
      { unidade: 'Cardiologia', score: 89.4, variacao: 1.1, severidade: 'atencao' },
      { unidade: 'Ginecologia', score: 88.9, variacao: 1.4, severidade: 'atencao' },
    ],
    needsAttention: [
      { unidade: 'Emergência Adulto', score: 82.3, variacao: -2.8, severidade: 'grave' },
      { unidade: 'Pediatria', score: 81.7, variacao: -1.9, severidade: 'grave' },
      { unidade: 'Clínica Médica', score: 80.4, variacao: -1.2, severidade: 'atencao' },
      { unidade: 'Ortopedia', score: 78.5, variacao: -3.4, severidade: 'critico' },
      { unidade: 'Hemodinâmica', score: 76.9, variacao: -2.1, severidade: 'critico' },
    ],
    monthlyComparison: [
      { mes: 'Jan', melhores: 90.3, atencao: 78.9, mediaRede: 84.5 },
      { mes: 'Fev', melhores: 91.4, atencao: 79.6, mediaRede: 85.2 },
      { mes: 'Mar', melhores: 92.1, atencao: 80.1, mediaRede: 85.6 },
      { mes: 'Abr', melhores: 93.8, atencao: 81.3, mediaRede: 86.2 },
      { mes: 'Mai', melhores: 94.5, atencao: 82.7, mediaRede: 87.1 },
      { mes: 'Jun', melhores: 94.9, atencao: 83.1, mediaRede: 87.5 },
    ],
  },
  cost: {
    averageCostPerPatient: 2450,
    averageCostVariation: '+6,4% em 6 meses',
    specialtyBreakdown: [
      { especialidade: 'Cirurgia Geral', custoMedio: 2680, contribuicao: 22 },
      { especialidade: 'Cardiologia', custoMedio: 3120, contribuicao: 18 },
      { especialidade: 'Oncologia', custoMedio: 3580, contribuicao: 16 },
      { especialidade: 'Ortopedia', custoMedio: 2140, contribuicao: 14 },
      { especialidade: 'UTI', custoMedio: 4020, contribuicao: 12 },
      { especialidade: 'Pediatria', custoMedio: 1890, contribuicao: 8 },
    ],
    monthlyTrend: [
      { mes: 'Jan', custoReal: 2120, custoOrcado: 2050 },
      { mes: 'Fev', custoReal: 2230, custoOrcado: 2140 },
      { mes: 'Mar', custoReal: 2190, custoOrcado: 2100 },
      { mes: 'Abr', custoReal: 2340, custoOrcado: 2220 },
      { mes: 'Mai', custoReal: 2410, custoOrcado: 2300 },
      { mes: 'Jun', custoReal: 2480, custoOrcado: 2360 },
    ],
  },
  quality: {
    indicators: [
      {
        indicador: 'Taxa de Infecção Hospitalar',
        valor: 1.2,
        unidade: '%',
        meta: 2.0,
        severidade: 'estavel',
        descricao: 'Monitoramento baseado em vigilância epidemiológica ativa.',
      },
      {
        indicador: 'Taxa de Mortalidade Ajustada',
        valor: 2.8,
        unidade: '%',
        meta: 3.0,
        severidade: 'estavel',
        descricao: 'Taxa ajustada por case-mix clínico e risco cirúrgico.',
      },
      {
        indicador: 'Tempo Médio de Atendimento Emergência',
        valor: 32,
        unidade: 'min',
        meta: 28,
        severidade: 'grave',
        descricao: 'Tempo entre chegada e primeiro atendimento médico.',
      },
      {
        indicador: 'Cancelamento de Cirurgias',
        valor: 3.2,
        unidade: '%',
        meta: 4.0,
        severidade: 'atencao',
        descricao: 'Incluso cancelamento clínico e operacional nas últimas 8 semanas.',
      },
    ],
    timeline: [
      { mes: 'Jan', infeccao: 1.6, mortalidade: 3.1, cancelamento: 4.0 },
      { mes: 'Fev', infeccao: 1.4, mortalidade: 3.0, cancelamento: 3.6 },
      { mes: 'Mar', infeccao: 1.3, mortalidade: 2.9, cancelamento: 3.4 },
      { mes: 'Abr', infeccao: 1.2, mortalidade: 2.8, cancelamento: 3.1 },
      { mes: 'Mai', infeccao: 1.1, mortalidade: 2.7, cancelamento: 3.0 },
      { mes: 'Jun', infeccao: 1.0, mortalidade: 2.6, cancelamento: 2.8 },
    ],
  },
  charts: {
    trend: [
      { mes: 'Jan', ocupacao: 88, mortalidade: 3.1, satisfacao: 4.0, severidade: 'atencao' },
      { mes: 'Fev', ocupacao: 91, mortalidade: 2.9, satisfacao: 4.1, severidade: 'grave' },
      { mes: 'Mar', ocupacao: 89, mortalidade: 2.8, satisfacao: 4.0, severidade: 'grave' },
      { mes: 'Abr', ocupacao: 93, mortalidade: 2.7, satisfacao: 4.3, severidade: 'atencao' },
      { mes: 'Mai', ocupacao: 95, mortalidade: 2.6, satisfacao: 4.2, severidade: 'critico' },
      { mes: 'Jun', ocupacao: 92, mortalidade: 2.5, satisfacao: 4.4, severidade: 'grave' },
    ],
    heatmap: [
      { ala: 'UTI Adulto', periodo: 'Manhã', ocupacao: 97, severidade: 'critico' },
      { ala: 'UTI Adulto', periodo: 'Tarde', ocupacao: 95, severidade: 'critico' },
      { ala: 'UTI Adulto', periodo: 'Noite', ocupacao: 93, severidade: 'grave' },
      { ala: 'Clínica Médica', periodo: 'Manhã', ocupacao: 88, severidade: 'grave' },
      { ala: 'Clínica Médica', periodo: 'Tarde', ocupacao: 85, severidade: 'atencao' },
      { ala: 'Clínica Médica', periodo: 'Noite', ocupacao: 83, severidade: 'atencao' },
      { ala: 'Oncologia', periodo: 'Manhã', ocupacao: 86, severidade: 'grave' },
      { ala: 'Oncologia', periodo: 'Tarde', ocupacao: 82, severidade: 'atencao' },
      { ala: 'Oncologia', periodo: 'Noite', ocupacao: 79, severidade: 'estavel' },
    ],
    pareto: [
      { causa: 'Fila cirúrgica oncológica', impactoFinanceiro: 420, cumulativo: 32, severidade: 'critico' },
      { causa: 'Glosas APAC', impactoFinanceiro: 310, cumulativo: 56, severidade: 'grave' },
      { causa: 'Superlotação PS', impactoFinanceiro: 260, cumulativo: 75, severidade: 'grave' },
      { causa: 'Absenteísmo equipe', impactoFinanceiro: 180, cumulativo: 89, severidade: 'atencao' },
      { causa: 'Custos insumos alto custo', impactoFinanceiro: 150, cumulativo: 100, severidade: 'atencao' },
    ],
    realtime: [
      {
        id: 'centro-cirurgico',
        titulo: 'Centro Cirúrgico',
        valor: '87% capacidade',
        variacao: '+6 casos agendados',
        severidade: 'grave',
        icon: 'target',
        descricao: 'Necessidade de redistribuição de equipe anestésica.',
      },
      {
        id: 'uti-neonatal',
        titulo: 'UTI Neonatal',
        valor: '94% ocupação',
        variacao: '+2 transferências previstas',
        severidade: 'critico',
        icon: 'shield-alert',
        descricao: 'Plano contingência ativado com unidades parceiras.',
      },
      {
        id: 'farmacia-alto-custo',
        titulo: 'Farmácia Alto Custo',
        valor: 'Cobertura 11 dias',
        variacao: '-2 dias na semana',
        severidade: 'grave',
        icon: 'pie-chart',
        descricao: 'Reforçar pedidos emergenciais para onco e hemato.',
      },
      {
        id: 'satisfacao-digital',
        titulo: 'Feedback Digital',
        valor: '91% positivos',
        variacao: '+4pts',
        severidade: 'estavel',
        icon: 'users',
        descricao: 'Tracking de experiência multicanal com resposta em 12h.',
      },
    ],
  },
};

export const getHospitalPerformanceSnapshot = (): HospitalPerformanceSnapshot =>
  hospitalPerformanceSnapshot;
