// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://droygvpcwkrdzfdtxqsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyb3lndnBjd2tyZHpmZHR4cXNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5OTI0MzgsImV4cCI6MjA3MjU2ODQzOH0.wCKXYKMbwEgFLaLWNSqitvmteK85HG5yTMAsuHouVfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const authOptions = {
  persistSession: true,
  autoRefreshToken: true,
  ...(typeof window !== 'undefined' ? { storage: window.localStorage } : {}),
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: authOptions,
});
